/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ua.edu.odeku.pet.gui.tests.sequencing;

/**
 *
 * @author Aleo
 */
public class ItemSequencingPanel extends javax.swing.JPanel {

    /**
     * Creates new form ItemSequencingPanel
     */
    public ItemSequencingPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel = new javax.swing.JLabel();
        jTextField = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();

        jLabel.setText("участок последовательности:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator1)
                    .addComponent(jTextField, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 283, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the String text
     */
    public String getjLabel() {
        return jLabel.getText();
    }

    /**
     * @param String text for jLabel
     */
    public void setjLabel(String text) {
        this.jLabel.setText(text);
    }

    /**
     * @return the text from jTextField
     */
    public String getjTextField() {
        return jTextField.getText();
    }

    /**
     * @param String the text for jTextField
     */
    public void setjTextField(String text) {
        this.jTextField.setText(text);
    }

    /**
     * @param jSeparator1 the jSeparator1 to set
     */
    public void setjSeparator(boolean flag) {
        this.jSeparator1.setVisible(flag);
    }
    
    
}
