/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ua.edu.odeku.pet.gui.tests;

import java.awt.BorderLayout;
import ua.edu.odeku.pet.gui.tests.alternativeChoice.AlternativePanel;
import ua.edu.odeku.pet.gui.tests.matched.MatchedPanel;
import ua.edu.odeku.pet.gui.tests.select.SelectedPanel;
import ua.edu.odeku.pet.gui.tests.sequencing.SequencingPanel;
import ua.edu.odeku.pet.util.SMS;

/**
 *
 * @author Aleo
 */
public class SelectedTypeAskPanel extends javax.swing.JPanel {
    SelectedPanel selectedPanel;
    AlternativePanel alternativeChoicePanel;
    MatchedPanel matchedPanel;
    SequencingPanel sequencingPanel;
    
    /**
     * Метод возращает тот объект который сейчас отображаеться для заполнений
     * @return Questionable который можно будет сохранить
     */
    public Questionable returnItemTest(){
        if(jPanel1.getComponentCount() == 0){
            return null;
        }
        return (Questionable) jPanel1.getComponent(0);
    }
    
    /**
     * Creates new form SelectedTypeAskPanel
     */
    public SelectedTypeAskPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonApply = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        typeAskPanel1 = new ua.edu.odeku.pet.gui.tests.TypeAskPanel();

        jButtonApply.setText("Применить");
        jButtonApply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonApplyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 171, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(typeAskPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                        .addComponent(jButtonApply)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonApply)
                    .addComponent(typeAskPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonApplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonApplyActionPerformed
        String type  = typeAskPanel1.getTypeAsk();
        jPanel1.setLayout(new BorderLayout());
        jPanel1.removeAll();
        switch (type) {
            case "SelectedTest":
                if(selectedPanel == null){
                    selectedPanel = new SelectedPanel();
                }
                //selectedPanel.setSize(jPanel1.getSize());
                jPanel1.add(selectedPanel, BorderLayout.CENTER);
                break;
            case "AlternativeChoice":
                if(alternativeChoicePanel == null){
                    alternativeChoicePanel = new AlternativePanel();
                }
                //alternativeChoicePanel.setSize(jPanel1.getSize());
                jPanel1.add(alternativeChoicePanel, BorderLayout.NORTH);
                break;
            case "Matched":
                if(matchedPanel == null){
                    matchedPanel = new MatchedPanel();
                }
                jPanel1.add(matchedPanel);
                break;
            case "Sequencing":
                if(sequencingPanel == null){
                    sequencingPanel = new SequencingPanel();
                }
                jPanel1.add(sequencingPanel);
                break;
            default:
                SMS.message("Еще не реализовано!!!");
                break;
        }
        jPanel1.updateUI();
        
    }//GEN-LAST:event_jButtonApplyActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonApply;
    private javax.swing.JPanel jPanel1;
    private ua.edu.odeku.pet.gui.tests.TypeAskPanel typeAskPanel1;
    // End of variables declaration//GEN-END:variables
}
