/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ua.edu.odeku.pet.gui.tests;

/**
 *
 * @author Aleo
 */
public class TypeAskPanel extends javax.swing.JPanel {

    /**
     * Creates new form TypeAskPanel
     */
    public TypeAskPanel() {
        initComponents();
    }
    
    /**
     * Вернет строку в которой указан тип теста
     * @return AlternativeChoice - альтернативный выбор,
     *         Matched - выбор соответствия
     *         Sequencing - установление последовательности
     *         SelectedTest - выбор вариантов
     */
    public String getTypeAsk(){
        if(jRadioButtonAlternativeChoice.isSelected()){
            return "AlternativeChoice";
        } else if(jRadioButtonMatched.isSelected()) {
            return "Matched";
        } else if(jRadioButtonSequencing.isSelected()){
            return "Sequencing";
        } else {
            return "SelectedTest";
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jRadioButtonSelectedTest = new javax.swing.JRadioButton();
        jRadioButtonAlternativeChoice = new javax.swing.JRadioButton();
        jRadioButtonMatched = new javax.swing.JRadioButton();
        jRadioButtonSequencing = new javax.swing.JRadioButton();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Тип теста"));

        buttonGroup.add(jRadioButtonSelectedTest);
        jRadioButtonSelectedTest.setSelected(true);
        jRadioButtonSelectedTest.setText("Множественный выбор");

        buttonGroup.add(jRadioButtonAlternativeChoice);
        jRadioButtonAlternativeChoice.setText("Альтернативный выбор");

        buttonGroup.add(jRadioButtonMatched);
        jRadioButtonMatched.setText("Установление соответствия");

        buttonGroup.add(jRadioButtonSequencing);
        jRadioButtonSequencing.setText("Установление последовательности");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jRadioButtonSelectedTest)
                .addGap(18, 18, 18)
                .addComponent(jRadioButtonMatched, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jRadioButtonAlternativeChoice)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jRadioButtonSequencing))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonSelectedTest)
                    .addComponent(jRadioButtonMatched))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonAlternativeChoice)
                    .addComponent(jRadioButtonSequencing)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButtonAlternativeChoice;
    private javax.swing.JRadioButton jRadioButtonMatched;
    private javax.swing.JRadioButton jRadioButtonSelectedTest;
    private javax.swing.JRadioButton jRadioButtonSequencing;
    // End of variables declaration//GEN-END:variables
}
