/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import gui.dictionaries.DepartmentFrame;
import gui.dictionaries.FacultyFrame;
import gui.dictionaries.GroupsFrame;
import gui.dictionaries.SubjectFrame;
import gui.dictionaries.TeacherFrame;
import gui.dictionaries.TypeWorkFrame;
import gui.tests.TestsFrame;
import javax.swing.JFrame;
import settings.ConfigureProgramm;

/**
 *
 * @author Aleo
 */
public class MainFormPET extends javax.swing.JFrame {

    /**
     * Creates new form MainFormPET
     */
    public MainFormPET() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jButtonNewTest = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuDictionaries = new javax.swing.JMenu();
        jMenuItemDepartment = new javax.swing.JMenuItem();
        jMenuItemFaculty = new javax.swing.JMenuItem();
        jMenuItemSubject = new javax.swing.JMenuItem();
        jMenuItemTeachers = new javax.swing.JMenuItem();
        jMenuItemMark = new javax.swing.JMenuItem();
        jMenuItemTypeWork = new javax.swing.JMenuItem();
        jMenuItemGroup = new javax.swing.JMenuItem();
        jMenuItemStudent = new javax.swing.JMenuItem();
        jMenuSettings = new javax.swing.JMenu();
        jCheckBoxMenuItemIsDebag = new javax.swing.JCheckBoxMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PET");
        setAutoRequestFocus(false);
        setLocationByPlatform(true);
        setMinimumSize(new java.awt.Dimension(40, 40));
        setModalExclusionType(java.awt.Dialog.ModalExclusionType.TOOLKIT_EXCLUDE);

        jToolBar1.setRollover(true);

        jButtonNewTest.setText("Новый тест");
        jButtonNewTest.setFocusable(false);
        jButtonNewTest.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonNewTest.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonNewTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNewTestActionPerformed(evt);
            }
        });
        jToolBar1.add(jButtonNewTest);

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenuDictionaries.setText("Словари");

        jMenuItemDepartment.setText("Кафедры");
        jMenuItemDepartment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemDepartmentActionPerformed(evt);
            }
        });
        jMenuDictionaries.add(jMenuItemDepartment);

        jMenuItemFaculty.setText("Факультет");
        jMenuItemFaculty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemFacultyActionPerformed(evt);
            }
        });
        jMenuDictionaries.add(jMenuItemFaculty);

        jMenuItemSubject.setText("Предметы");
        jMenuItemSubject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSubjectActionPerformed(evt);
            }
        });
        jMenuDictionaries.add(jMenuItemSubject);

        jMenuItemTeachers.setText("Преподаватели");
        jMenuItemTeachers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemTeachersActionPerformed(evt);
            }
        });
        jMenuDictionaries.add(jMenuItemTeachers);

        jMenuItemMark.setText("Оценки");
        jMenuItemMark.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemMarkActionPerformed(evt);
            }
        });
        jMenuDictionaries.add(jMenuItemMark);

        jMenuItemTypeWork.setText("Типы работ");
        jMenuItemTypeWork.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemTypeWorkActionPerformed(evt);
            }
        });
        jMenuDictionaries.add(jMenuItemTypeWork);

        jMenuItemGroup.setText("Группы");
        jMenuItemGroup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemGroupActionPerformed(evt);
            }
        });
        jMenuDictionaries.add(jMenuItemGroup);

        jMenuItemStudent.setText("Студенты");
        jMenuDictionaries.add(jMenuItemStudent);

        jMenuBar1.add(jMenuDictionaries);

        jMenuSettings.setText("Настройки");

        jCheckBoxMenuItemIsDebag.setSelected(true);
        jCheckBoxMenuItemIsDebag.setText("Режим отладки");
        jCheckBoxMenuItemIsDebag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMenuItemIsDebagActionPerformed(evt);
            }
        });
        jMenuSettings.add(jCheckBoxMenuItemIsDebag);

        jMenuBar1.add(jMenuSettings);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 891, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(461, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemDepartmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemDepartmentActionPerformed
        DepartmentFrame df = new DepartmentFrame();
        df.setVisible(true);
    }//GEN-LAST:event_jMenuItemDepartmentActionPerformed

    private void jMenuItemTeachersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemTeachersActionPerformed
        TeacherFrame tf = new TeacherFrame();
        tf.setVisible(true);
    }//GEN-LAST:event_jMenuItemTeachersActionPerformed

    private void jCheckBoxMenuItemIsDebagActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItemIsDebagActionPerformed
        ConfigureProgramm.setDEBAG(jCheckBoxMenuItemIsDebag.getState());
    }//GEN-LAST:event_jCheckBoxMenuItemIsDebagActionPerformed

    private void jMenuItemFacultyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemFacultyActionPerformed
        FacultyFrame ff = new FacultyFrame();
        ff.setVisible(true);
    }//GEN-LAST:event_jMenuItemFacultyActionPerformed

    private void jMenuItemGroupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemGroupActionPerformed
        GroupsFrame frame = new GroupsFrame();
        frame.setVisible(true);
        frame.updateTable();
    }//GEN-LAST:event_jMenuItemGroupActionPerformed

    private void jMenuItemTypeWorkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemTypeWorkActionPerformed
        TypeWorkFrame frame = new TypeWorkFrame();
        frame.setVisible(true);
        frame.updateTable();
    }//GEN-LAST:event_jMenuItemTypeWorkActionPerformed

    private void jMenuItemSubjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSubjectActionPerformed
        SubjectFrame frame = new SubjectFrame();
        frame.setVisible(true);
        frame.updateTable();
    }//GEN-LAST:event_jMenuItemSubjectActionPerformed

    private void jButtonNewTestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNewTestActionPerformed
        TestsFrame frame = new TestsFrame();
        frame.setVisible(true);
    }//GEN-LAST:event_jButtonNewTestActionPerformed

    private void jMenuItemMarkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemMarkActionPerformed

    }//GEN-LAST:event_jMenuItemMarkActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        settings.ConfigureProgramm.loadConfig();
        
        try {
            javax.swing.UIManager.setLookAndFeel(javax.swing.UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFormPET.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        database.DataBaseConnect.createTables();
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MainFormPET mf = new MainFormPET();
                mf.setExtendedState(JFrame.MAXIMIZED_BOTH);
                
                mf.setVisible(true);
                mf.jCheckBoxMenuItemIsDebag.setState(false);
                ConfigureProgramm.setDEBAG(false);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonNewTest;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItemIsDebag;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuDictionaries;
    private javax.swing.JMenuItem jMenuItemDepartment;
    private javax.swing.JMenuItem jMenuItemFaculty;
    private javax.swing.JMenuItem jMenuItemGroup;
    private javax.swing.JMenuItem jMenuItemMark;
    private javax.swing.JMenuItem jMenuItemStudent;
    private javax.swing.JMenuItem jMenuItemSubject;
    private javax.swing.JMenuItem jMenuItemTeachers;
    private javax.swing.JMenuItem jMenuItemTypeWork;
    private javax.swing.JMenu jMenuSettings;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
